// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250602121121_LeggTilForesporselModel")]
    partial class LeggTilForesporselModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Bakdel.Contorllers.Models.Bruker", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("brukernavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("passord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Brukere");
                });

            modelBuilder.Entity("Bakdel.Contorllers.Models.Foresporsel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("akseptert")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dato")
                        .HasColumnType("TEXT");

                    b.Property<int>("eierID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("passerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Foresporsler");
                });

            modelBuilder.Entity("Bakdel.Contorllers.Models.Hund", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("alder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("spesielleBehov")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Hunder");
                });

            modelBuilder.Entity("Bakdel.Contorllers.Models.HundeEier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("brukernavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("hundeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("rolle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("HundeEiere");
                });

            modelBuilder.Entity("Bakdel.Contorllers.Models.HundePasser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("brukernavn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("omraade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("pris")
                        .HasColumnType("INTEGER");

                    b.Property<string>("rolle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("HundePassere");
                });
#pragma warning restore 612, 618
        }
    }
}
